apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - image: okteto.dev/blog:latest
        name: blog