apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cache
  labels:
    app.kubernetes.io/instance: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache
  serviceName: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
      - name: cache
        image: redis
        resources:
          limits:
            memory: "100Mi"
            cpu: "50m"
        

---

apiVersion: v1
kind: Service
metadata:
  name: cache
  labels:
    app.kubernetes.io/instance: django
spec:
  type: ClusterIP  
  ports:
  - name: cache
    port: 6379
  selector:
    app: cache
