apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - image: ${OKTETO_BUILD_BLOG_IMAGE}
        name: blog

---

apiVersion: v1
kind: Service
metadata:
  name: blog
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "blog"
    port: 8080
  selector:
    app: blog
